---
- name: Converge
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Include vsphere_tagging role
      ansible.builtin.include_role:
        name: vsphere_tagging
      vars:
        vsphere_tagging_vcenter:
          hostname: "{{ lookup('env', 'VCENTER_HOSTNAME') | default('localhost', true) }}"
          username: "{{ lookup('env', 'VCENTER_USERNAME') | default('user', true) }}"
          password: "{{ lookup('env', 'VCENTER_PASSWORD') | default('pass', true) }}"
          validate_certs: false
        vsphere_tagging_failure_domains: []
        vsphere_tagging_region: region-1
