---
- name: Converge
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Include vsphere_datacenter_config role
      ansible.builtin.include_role:
        name: vsphere_datacenter_config
      vars:
        vsphere_datacenter_config_vcenter:
          hostname: "{{ lookup('env', 'VCENTER_HOSTNAME') | default('localhost', true) }}"
          username: "{{ lookup('env', 'VCENTER_USERNAME') | default('user', true) }}"
          password: "{{ lookup('env', 'VCENTER_PASSWORD') | default('pass', true) }}"
          validate_certs: false
        vsphere_datacenter_config_topology:
          datacenters: []
