---
galaxy_info:
  role_name: vsphere_datacenter_config
  author: OpenShift SPLAT Team
  description: Configure vSphere datacenters, clusters, DRS, and HA
  company: Red Hat
  license: Apache-2.0
  min_ansible_version: "2.16"

  platforms:
    - name: EL
      versions:
        - "8"
        - "9"

  galaxy_tags:
    - vsphere
    - vmware
    - datacenter
    - cluster
    - drs
    - ha

dependencies: []

collections:
  - community.vmware
